str1 = input("enter first string:\n")
print("first string is:\t--> ",set(str1))
str2 = input("enter second string:\n")
print("second string is:\t--> ",set(str2))
print("not common",str(set(str1)^set(str2)))